;AUTHORS : OFIR POST 308401066 AND EMRI BIRAN 203798897	
;DATE : 2/1/18
;FILE NAME: EX2.ASM
;
;PURPOSE: IN THIS CODE 

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
#include <ADUC841.h>
CSEG AT 0000H
	JMP MAIN
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
CSEG AT 0033H ; ADDRESS OF ADC INTERUPT
	JMP ADC_INT ; 
RETI
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
CSEG AT 0100H ; MAIN

MAIN:

	MOV ADCCON1, #0BAH ; 
	;[EN(1)][ACCORDING TO V REFFERNCE(0)][DIVIDE BY 2(11)][AMOUNT OF CYCLES TO SAMPLE(10)][SAMPLE WHEN TIMER2 IS IN OVERFLOW(1)][OUTER(0)]
	CLR CCONV ; CLR BIT 5 OF ADCCON2
	ANL ADCCON2,#090H ;TURN ON ADC
	ANL T2CON, #044H ;TIMER 2 CONFIG
	SETB TR2; ENABLE TIMER 2
	ANL DACCON , #07FH ;DAC CONFIG
	ORL DACCON , #2DH 
	;-----SET INTERUPTS-----
	SETB EADC ; TURN ON ADC INTERRUPT
	SETB EA ; GLOBAL INTERRUPT ENABLE
	JMP $	;INF LOOP

ADC_INT:
		MOV DAC0L,ADCDATAL ; COPY ADC OUTPUT TO DAC INPUT
		MOV DAC0H,ADCDATAH
RETI
		
END