
#include <ADUC841.h>
LED     EQU     P3.4  
CSEG AT 0000H
	JMP MAIN

CSEG AT 000BH ; ADDRESS OF TIMER 0 INTERUPT
	CPL LED ; activate led
RETI
;JMP TIMER0_INT; WE JMP TO OTHER LOCATION BECUASE OF SHORT MEMORY

CSEG AT 0023H ; ADDRESS OF SERIAL INTERUPT
CLR ES ; DISABLE SERIAL PORT INTERUPT
SETB FLAG_UART
RETI
;JMP SERIAL ; WE JMP TO OTHER LOCATION BECUASE OF SHORT MEMORY

CSEG AT 0100H ; MAIN

MAIN:
	MOV T3FD , #00100000B ; SET T3FD TO 32 AS CACULATE
	ANL T3CON , #11111011B ;REPRESENT DIV=3, TURN ON BIT7 - T3BAUDEN
	ORL T3CON , #10000011B ;REPRESENT DIV=3, TURN ON BIT7 - T3BAUDEN
	CLR SM0  ;TURN OFF BIT 7 IN SCON - UART AT 8 BIT MODE
	SETB SM1 ;TURN ON BIT 6 IN SCON - UART AT 8 BIT MODE
	SETB REN ;TURN ON BIT 4 SCON - RECIVE DATA ENABLE
	ANL TMOD , #0F0H ; TURN ON BIT 0 TO SET TIMER0 TO MODE 1
	ORL TMOD , #02H ; TURN OFF BIT 1 TO SET TIMER0 TO MODE 1
	MOV TH0 , #000D
	SETB TR0
	;-----SET INTERUPTS-----
	SETB ET0 ; TIMER0 INTERRUPT
	SETB ES ; ENABLE SERIAL PORT INTERUPT
	SETB EA ; GLOBAL INTERRUPT ENABLE
	MOV DPTR , #TO_SCREEN ; PRINT MENU TO SCREEN
	SETB TI ; WILL CAUSE AN INTERUPT TO PRINT
LOOPER:
	JNB FLAG_UART,$
	CLR FLAG_UART
	JBC RI,RI_ON ;TURN OFF RI AND JMP TO SEND IT BACK
	CLR TI ; CLEAR THE TRANSMIT FLAG OF THE UART
	SETB ES ; ENABLE SERIAL PORT INTERUPT
	;TRANSMINT INTERUPT
	PUSH ACC ;SAVE THE ACCUMLATOR
	CLR A
	MOVC A , @A+DPTR ; DPTR HOLD THE ADDRESS TO THE LABEL THAT REPRESNT THE LETTER THAT SUPPOSED TO BE PRINT
	JZ IN_NULL ; DO NOT PRINT OF THE LETTER THAT A HOLDS IS NULL
	MOV SBUF , A ; SEND A TO SBUF WILL PRINT IT
	INC DPTR ; FOR READING THE NEXT LETTER IN THE STRING
IN_NULL: ;JUMP TO THIS POINT WHEN WEPINISH THE STRING 
	POP ACC 
JMP LOOPER
	
RI_ON:
	SETB ES ; ENABLE SERIAL PORT INTERUPT
	MOV R2 , SBUF ; REGISTER R2 WILL GET THE LETTER THAT ENTERED THE SBUF FROM THE 
	CJNE R2 , #'1' ,CHECK_2 ;check if r2 hold 1, if not jump to check_2
	MOV TH0 , #234D ; WE NEED A PEREIOD OF 4 us so every 2 us interrupt will occured 
					   ;our clock period is 0.0904Us so we need to count 22 times
					   ; 256-234 = 22
	JMP LOOPER
	CHECK_2:
		CJNE R2 , #'2' , CHECK_3
		MOV TH0 , #145D
	JMP LOOPER
	CHECK_3:
		CJNE R2 , #'3' , ERROR_MSG
		MOV TH0 , #000D
	JMP LOOPER
	ERROR_MSG:
		MOV DPTR , #ERR_MSG
		SETB TI	
	JMP LOOPER ; inf loop

	

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
CSEG AT 0200H ; 

ERR_MSG:   DB 'ERROR - WRONG KEY PRESSED'
		   DB 13 ; CARRIAGE RETURN
		   DB 10 ; NEW LINE
		   DB 0 ; NULL	
 
TO_SCREEN: DB '1. period of 4 us'
		   DB 13 ; CARRIAGE RETURN
		   DB 10 ; NEW LINE
		   DB '2. period of 20 us '
		   DB 13 ; CARRIAGE RETURN
		   DB 10 ; NEW LINE
		   DB '3. period of 46 us'
		   DB 13 ; CARRIAGE RETURN
		   DB 10 ; NEW LINE
		   DB 0 ; NULL	
		   
BSEG FLAG_UART: DBIT 1

END


